module Rice
  class Buffer≺char≻
    def initialize: (value: Integer) -> NilClass
               | (value: Integer, size: Integer) -> NilClass
    def []: (index: Integer) -> String
    def []=: (arg_0: Integer, arg_1: String) -> NilClass
    def bytes: () -> Integer
          | (arg_0: Integer) -> Integer
    def data: () -> Rice::Pointer≺char≻
    def release: () -> Rice::Pointer≺char≻
    def size: () -> Integer
    def to_ary: () -> Array
           | (arg_0: Integer) -> Array
    def to_s: () -> Integer
  end
end
