module Bmp
  class Bitmap
    def !: () -> TrueClass
    def !=: (image: Bmp::Bitmap) -> TrueClass
    def ==: (image: Bmp::Bitmap) -> TrueClass
    def []: (i: Integer) -> Bmp::Pixel
       | (i: Integer) -> Bmp::Pixel
    def []=: (arg_0: Integer, arg_1: Bmp::Pixel) -> NilClass
    def initialize: () -> NilClass
               | (filename: String) -> NilClass
               | (width: Integer, height: Integer) -> NilClass
    def assign: (image: Bmp::Bitmap) -> Bmp::Bitmap
           | (image: Bmp::Bitmap) -> Bmp::Bitmap
    def clear: (pixel: Bmp::Pixel) -> NilClass
    def draw_circle: (center_x: Integer, center_y: Integer, radius: Integer, color: Bmp::Pixel) -> NilClass
    def draw_line: (x1: Integer, y1: Integer, x2: Integer, y2: Integer, color: Bmp::Pixel) -> NilClass
    def draw_triangle: (x1: Integer, y1: Integer, x2: Integer, y2: Integer, x3: Integer, y3: Integer, color: Bmp::Pixel) -> NilClass
    def empty?: () -> TrueClass
    def fill_circle: (center_x: Integer, center_y: Integer, radius: Integer, color: Bmp::Pixel) -> NilClass
    def draw_rect: (x: Integer, y: Integer, width: Integer, height: Integer, color: Bmp::Pixel) -> NilClass
    def fill_rect: (x: Integer, y: Integer, width: Integer, height: Integer, color: Bmp::Pixel) -> NilClass
    def fill_triangle: (x1: Integer, y1: Integer, x2: Integer, y2: Integer, x3: Integer, y3: Integer, color: Bmp::Pixel) -> NilClass
    def flip_h: () -> Bmp::Bitmap
    def flip_v: () -> Bmp::Bitmap
    def get: (x: Integer, y: Integer) -> Bmp::Pixel
        | (x: Integer, y: Integer) -> Bmp::Pixel
    def height: () -> Integer
    def initialize_copy: (other: Bmp::Bitmap) -> NilClass
    def inspect: () -> String
    def load: (filename: Std::Filesystem::Path) -> NilClass
    def rotate_90_left: () -> Bmp::Bitmap
    def rotate_90_right: () -> Bmp::Bitmap
    def save: (filename: Std::Filesystem::Path) -> NilClass
    def set: (x: Integer, y: Integer, color: Bmp::Pixel) -> NilClass
    def size: () -> Integer
    def to_s: () -> String
    def width: () -> Integer
  end
end
