module Bmp
  class Pixel
    attr_accessor b: String
    attr_accessor g: String
    attr_accessor r: String

    def !=: (other: Bmp::Pixel) -> TrueClass
    def initialize: () -> NilClass
               | (rgb: Integer) -> NilClass
               | (red: String, green: String, blue: String) -> NilClass
    def ==: (other: Bmp::Pixel) -> TrueClass
    def assign: (arg_0: Bmp::Pixel) -> NilClass
    def inspect: () -> String
    def to_s: () -> String
  end
end
